"""
Django settings for WebDjango project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ
import logging
import urllib.parse

# Configure logging
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()

# Đọc file .env từ thư mục gốc của project
env_path = os.path.join(BASE_DIR, '.env')
logger.info(f"Looking for .env file at: {env_path}")

if os.path.exists(env_path):
    logger.info(f"Found .env file at: {env_path}")
    env.read_env(env_path)
    logger.info("Successfully loaded .env file")
else:
    logger.warning(f".env file not found at: {env_path}")
    # Thử tìm file .env ở các vị trí khác
    alternative_paths = [
        os.path.join(BASE_DIR.parent, '.env'),
        os.path.join(os.path.dirname(BASE_DIR), '.env'),
        os.path.join(os.getcwd(), '.env')
    ]
    
    for path in alternative_paths:
        if os.path.exists(path):
            logger.info(f"Found .env file at alternative location: {path}")
            env.read_env(path)
            logger.info("Successfully loaded .env file from alternative location")
            break
    else:
        logger.error("Could not find .env file in any location")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Phase 6: Use environment variable for SECRET_KEY
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-rcak$@*@l7r(!$rnucpdw0hvl+erbqhhbs_c=^88xzjg+&0fjj')

# SECURITY WARNING: don't run with debug turned on in production!
# Phase 6: Use environment variable for DEBUG
DEBUG = env.bool('DJANGO_DEBUG', default=True)

DEFAULT_OFFICE = env('DEFAULT_OFFICE', default='Hàn Mạc Tử')
DEFAULT_USERNAME = env('DEFAULT_USERNAME', default='admin')

# Phase 6: Restrict ALLOWED_HOSTS in production
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '207.148.69.229', '45.77.35.79'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'authentication.apps.AuthenticationConfig',
    'djongo',
    # 'channels',  # Comment out channels since we're not using WebSocket
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Phase 4: Enable GZip compression
    'authentication.security_middleware.SecurityHeadersMiddleware',  # Phase 6: Security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'authentication.middleware.MongoDBAuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'authentication.security_middleware.RateLimitMiddleware',  # Phase 6: Uncomment for global rate limiting
    # 'authentication.security_middleware.RequestLoggingMiddleware',  # Phase 6: Uncomment for audit logging
]

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Cấu hình messages
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

ROOT_URLCONF = 'WebDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'authentication.context_processors.debug_context',
                'authentication.context_processors.user_data_context',
                'authentication.context_processors.offices_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'WebDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# MongoDB settings – credentials come entirely from environment variables.
# If individual component vars are present, ALWAYS build the URI from them
# so that urllib.parse.quote_plus handles special characters in the password.
# Fall back to a pre-formed MONGODB_URI only when no component vars exist.
_mongo_password = env('MONGODB_PASSWORD', default='')
if _mongo_password:
    _mongo_user     = urllib.parse.quote_plus(env('MONGODB_USER', default='admin'))
    _mongo_password_enc = urllib.parse.quote_plus(_mongo_password)
    _mongo_host     = env('MONGODB_HOST', default='127.0.0.1')
    _mongo_port     = env('MONGODB_PORT', default='27017')
    _mongo_auth     = env('MONGODB_AUTH_SOURCE', default='admin')
    MONGODB_URI = (
        f'mongodb://{_mongo_user}:{_mongo_password_enc}'
        f'@{_mongo_host}:{_mongo_port}/?authSource={_mongo_auth}'
    )
else:
    # Fallback: pre-formed URI – caller must URL-encode special chars in password
    MONGODB_URI = env('MONGODB_URI')
MONGODB_DATABASE = env('MONGODB_DATABASE', default='mongodbCloud')

# External API Key for /api/users/ endpoint
API_SECRET_KEY = env('API_SECRET_KEY', default='')

# MongoDB Connection Settings - Optimized for performance
MONGODB_SETTINGS = {
    'maxPoolSize': 50,  # Reduced from 100
    'minPoolSize': 10,  # Reduced from 20
    'maxIdleTimeMS': 30000,  # Reduced from 60000
    'waitQueueTimeoutMS': 10000,  # Reduced from 20000
    'connectTimeoutMS': 10000,  # Reduced from 20000
    'socketTimeoutMS': 10000,  # Reduced from 20000
    'serverSelectionTimeoutMS': 10000,  # Reduced from 20000
    'retryWrites': True,
    'w': 'majority',
    'readPreference': 'primary',
    'compressors': 'zlib',
    'zlibCompressionLevel': 6,
    'retryReads': True,
    'directConnection': False,
    'appname': 'WebDjango',
    'heartbeatFrequencyMS': 10000,  # More frequent heartbeats
    'maxConnecting': 5,  # Limit concurrent connections
}

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': MONGODB_DATABASE,
        'CLIENT': {
            'host': MONGODB_URI,
            'authSource': 'admin',
            **MONGODB_SETTINGS
        },
        'CONN_MAX_AGE': 3600,  # 1 hour (reduced from 6 hours)
        'OPTIONS': {
            'connect': True,
        },
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }
}

# Redis settings
REDIS_HOST = os.getenv('REDIS_HOST', '207.148.69.229')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')

# Redis Connection Pool Settings

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD,
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 1000,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 2000,
                "socket_timeout": 50,
                "socket_connect_timeout": 50,
                "retry_on_timeout": True
            },
            "IGNORE_EXCEPTIONS": True,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer"
        },
        "KEY_PREFIX": "django",
        "TIMEOUT": 300
    }
}

# Connection Management Settings
CONNECTION_MANAGEMENT = {
    'cleanup_interval': 300,  # 5 minutes
    'idle_timeout': 600,  # 10 minutes
    'max_retries': 3,
    'retry_delay': 1,  # seconds
}

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = False if DEBUG else True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True

# CSRF settings
CSRF_COOKIE_SECURE = False  # Set to False for HTTP development
# Cross-Origin-Opener-Policy: chỉ bật khi chạy trên HTTPS/production
SECURE_CROSS_ORIGIN_OPENER_POLICY = None if DEBUG else 'same-origin'

CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read the cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # More permissive than 'Strict'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8001',
    'http://207.148.69.229',
    'http://207.148.69.229:8001',
    'http://207.148.69.229:81',
    'ws://207.148.69.229:8001',
    'ws://207.148.69.229:81',
    'http://45.77.35.79:8001'
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://207.148.69.229',
    'http://207.148.69.229:8001',
    'http://207.148.69.229:81'
    'http://45.77.35.79:8001'
]

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'elivibes0124@gmail.com'
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # App Password from Gmail
DEFAULT_FROM_EMAIL = 'elivibes0124@gmail.com'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Create necessary directories
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'media'), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'static'), exist_ok=True)  # Tạo thư mục static source
os.makedirs(os.path.join(BASE_DIR, 'staticfiles'), exist_ok=True)  # Tạo thư mục static collected

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Thư mục chứa static files source
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL configuration
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

AUTH_USER_MODEL = 'authentication.User'



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True




# Comment out WebSocket settings
"""
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}

ASGI_APPLICATION = 'WebDjango.asgi.application'

# WebSocket settings
CHANNELS_WS_PROTOCOLS = ['websocket']
CHANNELS_WS_ALLOWED_HOSTS = ['*']
CHANNELS_WS_ALLOWED_ORIGINS = ['*']
CHANNELS_WS_ALLOWED_METHODS = ['GET', 'POST']
CHANNELS_WS_ALLOWED_HEADERS = ['*']
CHANNELS_WS_ALLOWED_CREDENTIALS = True
CHANNELS_WS_MAX_CONNECTIONS = 1000
CHANNELS_WS_TIMEOUT = 60

# Uvicorn settings for WebSocket
UVICORN_WS_PING_INTERVAL = 20
UVICORN_WS_PING_TIMEOUT = 10
UVICORN_WS_MAX_MESSAGE_SIZE = 1024 * 1024  # 1MB
UVICORN_WS_MAX_QUEUE_SIZE = 1000
UVICORN_WS_MAX_CONNECTIONS = 1000
UVICORN_WS_TIMEOUT = 60
"""

# Logging settings - Phase 8: Enhanced logging with file rotation
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'json',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'audit.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 30,  # Keep more audit logs
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'authentication.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'daphne': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Application version for monitoring
APP_VERSION = '1.0.0'

# settings.py hoặc logging configuration
import sys
import logging.config

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': sys.stdout,  # Hoặc sys.stderr
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/app.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Quan trọng: đặt UTF-8 cho file
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Buộc console encoding sang UTF-8 (Windows workaround)
if sys.platform == 'win32':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except AttributeError:
        # Python < 3.7
        import codecs
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

logging.config.dictConfig(LOGGING)
